// this file was autogenerated, please do not modify
// AppIDs's Universalink URI Matching Configuration
export type ApplinksDetails = DetailsItems[];

// AppID's matching details
// Details of specific AppIDs uri matching configuration
export type DetailsItems = null;

// AppIDs
// Array of AppIDs
export type ItemsAppIDs = AppleAppSiteAssociationAppId[];

// ^[A_Z0_9]{10}\.([A_Za_z]{1}[A_Za_z\d_]*\.)+[A_Za_z][A_Za_z\d_]*$
// TeamID And AppID
// 10 character TeamID followed by AppID
export type AppleAppSiteAssociationAppId = string;

// Paths
// Array of paths to be matched against
export type ItemsPaths = PathsItems[];

// Path
// Single unique path to be matched against
export type PathsItems = null;

// AppIDs
// Array of multiple AppIDs
export type AppleAppSiteAssociationAppIds = AppleAppSiteAssociationAppId[];

export interface AppleAppSiteAssociation {
  // Webcredentials Config
  // Apple Webcredentials Config Schema
  webcredentials?: AppleAppSiteAssociationWebcredentials;
  // AppClip Config
  // Apple AppClip Config Schema
  appclips?: AppleAppSiteAssociationAppclips;
  // Universalink Configurations
  // Universalink Configurations Schema
  applinks: AppleAppSiteAssociationApplinks;
}

export interface AppleAppSiteAssociationAppclips {
  apps?: AppleAppSiteAssociationAppIds;
}

// URI Components
// Array of path components to be matched, available in later versions
export type ItemsComponents = AppleAppSiteAssociationComponent[];

// AppID component
// A component for uri matching
export type AppleAppSiteAssociationComponent = AppleAppSiteAssociationComponent;

export interface AppleAppSiteAssociationApplinks {
  // Always empty [] for UniversaLink, can be omitted in later versions
  apps?: Object[];
  // AppIDs's Universalink URI Matching Configuration
  details: DetailsItems[];
}

export interface AppleAppSiteAssociationWebcredentials {
  apps?: AppleAppSiteAssociationAppIds;
}

