// this file was autogenerated, please do not modify
export interface AppleAppSiteAssociation {
  // Webcredentials Config
  // Apple Webcredentials Config Schema
  webcredentials?: AppleAppSiteAssociationWebcredentials;
  // AppClip Config
  // Apple AppClip Config Schema
  appclips?: AppleAppSiteAssociationAppclips;
  // Universalink Configurations
  // Universalink Configurations Schema
  applinks: AppleAppSiteAssociationApplinks;
}

export type AppleAppSiteAssociationAppIds = AppleAppSiteAssociationAppId[];

export type AppleAppSiteAssociationAppId = `${string & {__brand: "^[A_Z0_9]{10}\.([A_Za_z]{1}[A_Za_z\d_]*\.)+[A_Za_z][A_Za_z\d_]*$"}}`;

export interface AppleAppSiteAssociationComponent {
  // Path component
  // Define path matching
  ''?: string;
  // Fragment component
  // Define fragment matching
  '#'?: string;
  // Query component
  // Define Query matching
  '?'?: Component;
  // Exclusion flag
  // Whether to exclude a specific match
  exclude?: boolean;
}

export type Component = object | string;

export interface AppleAppSiteAssociationWebcredentials {
  apps?: AppleAppSiteAssociationAppIds;
}

export interface AppleAppSiteAssociationAppclips {
  apps?: AppleAppSiteAssociationAppIds;
}

export interface AppleAppSiteAssociationApplinks {
  // Always empty [] for UniversaLink, can be omitted in later versions
  apps?: any[];
  // AppIDs's Universalink URI Matching Configuration
  details: DetailsItems[];
}

export interface DetailsItems {
  // AppIDs
  // Array of AppIDs
  appIDs?: AppleAppSiteAssociationAppId[];
  appID?: AppleAppSiteAssociationAppId;
  // Paths
  // Array of paths to be matched against
  paths?: AppleAppSiteAssociationAppId;
  // URI Components
  // Array of path components to be matched, available in later versions
  components?: AppleAppSiteAssociationAppId;
}

