// this file was autogenerated, please do not modify
export type File = string | null | FileFormat;

export interface Lego {
  // An array of your app's blocks.
  blocks: Items[];
  // An object mapping file objects to strings
  fileFormats?: object;
}

export interface Items {
  // The name of the block type
  type: string;
  // Path relative to root where the block will be stored
  path: string;
  // Is this a file? or a folder? False by default.
  isFile?: boolean;
  // Files making up the block
  files?: File[];
  file?: File;
}

export interface FileFormat {
  // Name of block file
  name: string;
  // Path to file template
  template?: string;
}

