// this file was autogenerated, please do not modify
export interface Lego {
  // An array of your app's blocks.
  blocks: BlocksItems[];
  // An object mapping file objects to strings
  fileFormats?: object;
}

export interface LegoFileFormat {
  // Name of block file
  name: string;
  // Path to file template
  template?: string;
}

// An array of your app's blocks.
export type LegoBlocks = BlocksItems[];

export type BlocksItems = null;

// Files making up the block
export type ItemsFiles = LegoFile[];

