// this file was autogenerated, please do not modify
export interface Lego {
  // An array of your app's blocks.
  blocks: BlocksItems[];
  // An object mapping file objects to strings
  fileFormats?: LegoFileFormats;
}

export type LegoFile = string | null | LegoFileFormat;

export interface LegoFileFormat {
  // Name of block file
  name: string;
  // Path to file template
  template?: string;
}

export interface BlocksItems {
  // The name of the block type
  type: string;
  // Path relative to root where the block will be stored
  path: string;
  // Is this a file? or a folder? False by default.
  isFile?: boolean;
  // Files making up the block
  files?: LegoFile[];
  file?: LegoFile;
}

export interface LegoFileFormats {
  [key: RegexMatched<".*">]: LegoFileFormat;
}

type RegexMatched<Pattern extends string> = `${string & {__brand: Pattern}}`;
