import 'dart:io';

import 'package:json_schema_to_code/src/generators/generator_typescript.dart';
import 'package:json_schema_to_code/src/schema.dart';
import 'package:json_schema_to_code/src/schema_store.dart';
import 'package:json_schema_to_code/src/utils/output.dart';
import 'package:json_schema_to_code/src/utils/path.dart';
import 'package:json_schema_to_code/src/utils/string.dart';

part 'typescript/class.dart';
part 'typescript/items.dart';

class BuilderTypescript extends GeneratorTypescript with Class, Items {
  BuilderTypescript(File schemaFile, SchemaStore schemaStore, this.uri)
    : assert(
        schemaStore.storedParsedObjects[uri] != null,
        'ERROR: schema object not found',
      ),
      super(schemaFile: schemaFile, schemaStore: schemaStore) {
    _schema = Schema(
      uri: uri,
      schemaStore: schemaStore,
      typeInferrer: _getInferredTypes,
    );
  }

  final Uri uri;
  late Schema _schema;

  /// Public
  void write(File outputFile) {
    OutputUtils.writeLine(
      outputFile,
      '// this file was autogenerated, please do not modify',
    );
    for (final MapEntry<Uri, Schema> schema
        in schemaStore.storedBuiltSchemas.entries) {
      _writeObject(outputFile, schema.value);
    }
  }

  /// Private
  void _writeObject(File outputFile, Schema schema) {
    if (schema.hasBeenWritten) return;

    // class interfaces
    if (schema.isClass) {
      writeClass(
        schema: schema,
        schemaStore: schemaStore,
        outputFile: outputFile,
      );
    } else if (schema.hasPrefixItems) {
      writePrefixItems(
        schema: schema,
        schemaStore: schemaStore,
        outputFile: outputFile,
        readTypeList: _readTypeList,
        typeListToString: _typeListToString,
      );
    } else if (schema.hasEnum) {
      writeEnum(
        schema: schema,
        schemaStore: schemaStore,
        outputFile: outputFile,
      );
    } else if (schema.hasPatternProperties) {
      writePatternProperties(
        schema: schema,
        schemaStore: schemaStore,
        outputFile: outputFile,
      );
    }
    schema.markAsWritten();
  }

  List<String> _readTypeList(Schema defSchema) {
    final List<String> someOfAndPrefixItems =
        <Uri>[...defSchema.someOfUris, ...defSchema.prefixItems].map((
          Uri someOfUri,
        ) {
          final Schema someOfUrisSchema = findSchemaByUri(someOfUri)!;
          for (final Uri? uriProperties
              in someOfUrisSchema.readTypeURIProperties().values) {
            if (uriProperties != null) {
              final Schema someOfUrisSchema = findSchemaByUri(uriProperties)!;
              return someOfUrisSchema.fullClassName();
            }
          }
          final String inferredType = _getInferredTypes(someOfUrisSchema);
          return inferredType;
        }).toList();
    if (someOfAndPrefixItems.isNotEmpty) return someOfAndPrefixItems;
    return defSchema.types;
  }

  String _typeListToString(
    List<String> types,
    Schema schema,
  ) {
    final bool isClassSchema = schema.isClass;
    final String fullClassName = schema.fullClassName();
    final bool hasItems = schema.hasItems || schema.hasItems;
    // https://github.com/jimblackler/jsonschematypes/blob/6054b6283f38b84a8642b6176369ba7526862132/codegen/src/main/java/net/jimblackler/jsonschematypes/codegen/TypeScriptBuilder.java#L56
    String typeOutput = '';
    for (final String type in types) {
      if (isClassSchema) {
        if (typeOutput.isNotEmpty) {
          typeOutput += ' | ';
        }
        typeOutput += fullClassName;
      } else if (type == 'array') {
        if (typeOutput.isNotEmpty) {
          typeOutput += ' | ';
        }
        if (!hasItems) {
          typeOutput += 'Object';
        } else {
          Schema? defSchema;
          final Schema itemsSchema = schema.getChildByUri();
          final Map<String, Uri?> uriProperties = itemsSchema
              .readTypeURIProperties();
          for (final Uri? uriProperty in uriProperties.values) {
            if (uriProperty != null) {
              defSchema = findSchemaByUri(uriProperty);
            }
          }
          final String itemsSchemaFullClassname = itemsSchema.fullClassName();
          typeOutput += defSchema?.fullClassName() ?? itemsSchemaFullClassname;
        }
        typeOutput += '[]';
      } else {
        if (typeOutput.isNotEmpty) {
          typeOutput += ' | ';
        }
        typeOutput += type;
      }
    }
    return typeOutput;
  }

  String _getInferredTypes(Schema schema) {
    if (schema.types.isNotEmpty) {
      return _typeListToString(
        schema.types,
        schema,
      );
    }
    final List<String> inferredTypes = <String>[];
    if (schema.enumValue != null &&
        schema.enumValue!.every((dynamic value) => value is String)) {
      (schema.enumValue! as List<String>).forEach(inferredTypes.add);
    }
    if (schema.readStringProperties().values.any(
      (String? property) => property != null,
    )) {
      inferredTypes.add('string');
    }
    if (schema.readNumericProperties().values.any(
      (num? property) => property != null,
    )) {
      inferredTypes.add('number');
    }
    if (schema.readListProperties().values.any(
          (num? property) => property != null,
        ) ||
        schema.uniqueItems ||
        schema.hasItems) {
      inferredTypes.add('array');
    }
    if (schema.readObjectProperties().values.any(
          (num? property) => property != null,
        ) ||
        schema.required ||
        schema.requiredProperties.isNotEmpty ||
        schema.dependentRequired.isNotEmpty ||
        schema.isClass ||
        schema.hasPropertyNames) {
      inferredTypes.add('object');
    }
    if (schema.defaultValue != null) {
      final Type dartType = schema.defaultValue.runtimeType;
      if (dartType == String) {
        inferredTypes.add('string');
      } else if (dartType == int || dartType == double) {
        inferredTypes.add('number');
      } else if (dartType == List) {
        inferredTypes.add('array');
      } else if (dartType == Object) {
        inferredTypes.add('object');
      }
    }
    return _typeListToString(
      inferredTypes,
      schema,
    );
  }

  Schema? findSchemaByUri(Uri uri) {
    return schemaStore.storedBuiltSchemas[uri];
  }
}
